# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Employ the official Node.js 18 Alpine image as the foundation
FROM node:18-alpine

# Establish the working directory
WORKDIR /app

# Copy package.json and package-lock.json hither
COPY package*.json ./

# Install the dependencies, as decreed
RUN npm ci

# Copy the source code and configuration files
COPY src/ ./src/
COPY tsconfig.json ./
COPY .env.example ./

# Compile TypeScript to JavaScript, most assuredly
RUN npm run build

# Create a non-root user for security's sake
RUN addgroup -g 1001 -S nodejs && \
    adduser -S mcp -u 1001

# Set file permissions with proper authority
RUN chown -R mcp:nodejs /app
USER mcp

# Expose port (if such be thy requirement)
# EXPOSE 3000

# Set environment variables
ENV NODE_ENV=production

# Launch the application
CMD ["npm", "start"]
